yespix.define('actor4w', 'actor', {
    actorMove: {
        'idle': true,
        'up': true,
        'right': true,
        'down': true,
        'left': true,
        'walk': true,
        'run': true,
        'jump': true,
        'damage': true,
        'crouch': true,
        'guard': true,
        'dead': true,
        'throw': true,
        'attack': true,
        'use': true,
        'default': 'idle',
    },
    actorDirection: 'down',
    actorAnims: {
        'walkup': 'walkup',
        'walkright': 'walkright',
        'walkdown': 'walkdown',
        'walkleft': 'walkleft',

        'idleup': 'idleup',
        'idleright': 'idleright',
        'idledown': 'idledown',
        'idleleft': 'idleleft',

        'runup': 'runup',
        'runright': 'runright',
        'rundown': 'rundown',
        'runleft': 'runleft',
    },
    actorInit: function(properties) {},
    init: function() {},
});
